#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, try using one of
#       them.
#
#   (2) Springloaded is incompatible with Windows cygwin shells that use newlines
#       from dos2unix conversions.
#
#   (3) If you have MSYS, find sh.exe and base the MSYSGIT set accordingly.
#
#   (4) The bash shell upstream from Cygwin is incompatible with minGW2 (issue #16334).
#       So it's better to use Git for Windows official shell, or even Git Bash in
#       "Git for Windows SDK".
#
#   (5) change the resolving of nonexistent commands
#       see https://github.com/gradle/gradle/issues/13847 for details
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"
WRAPPER_VERSION="0.0.1"
WRAPPER_PROPERTIES="gradle/wrapper/gradle-wrapper.properties"
EXEC_DIR="$(cd "$(dirname "$0")" && pwd)"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "error: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || { echo "error: Java is not installed." >&2; exit 1; }
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" ; then
    MAX_FD_LIMIT=$( ulimit -H -n ) &&
    [ "$MAX_FD_LIMIT" != 'unlimited' ] &&
    ulimit -n $MAX_FD_LIMIT
    if [ $? -ne 0 ] ; then
        warn "Could not set maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if "$darwin" ; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    GRADLE_OPTS=$( cygpath --path --mixed "$GRADLE_OPTS" )
    JAVACMD=$( cygpath --windows "$JAVACMD" )
    APP_HOME=$( cygpath --windows "$APP_HOME" )
    APP_JAR=$( cygpath --windows "$APP_JAR" )
    WRAPPER_PROPERTIES=$( cygpath --windows "$WRAPPER_PROPERTIES" )
    EXEC_DIR=$( cygpath --windows "$EXEC_DIR" )
    exec "$JAVACMD" \
        $GRADLE_OPTS \
        -classpath "$APP_JAR" \
        "-Dorg.gradle.appname=$APP_NAME" \
        "-Dorg.gradle.wrapper.properties=$WRAPPER_PROPERTIES" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
else
    exec "$JAVACMD" \
        $GRADLE_OPTS \
        -classpath "$APP_JAR" \
        "-Dorg.gradle.appname=$APP_NAME" \
        "-Dorg.gradle.wrapper.properties=$WRAPPER_PROPERTIES" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
fi
